version: '3.7'

services:
  wise-task-graph:
    image: ghcr.io/terross/wise-task-graph:main
    depends_on:
      - wise-task-mongo
    container_name: wise-task-graph
    ports:
      - "6565:6565"
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOKI_HOST=loki
      - TEMPO_HOST=tempo

  wise-task-plugin:
    image: ghcr.io/terross/wise-task-plugin:main
    depends_on:
      - wise-task-db
      - wise-task-graph
    container_name:  wise-task-plugin
    ports:
      - "6566:6566"
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOKI_HOST=loki
      - TEMPO_HOST=tempo

  wise-task-profile:
    image: ghcr.io/terross/wise-task-profile:main
    depends_on:
      - wise-task-db
    container_name: wise-task-profile
    ports:
      - "8082:8082"
      - "6567:6567"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOKI_HOST=loki
      - TEMPO_HOST=tempo

  wise-task-task:
    image: ghcr.io/terross/wise-task-task:main
    depends_on:
      - wise-task-db
      - wise-task-graph
      - wise-task-plugin
    container_name: wise-task-task
    ports:
      - "6568:6568"
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOKI_HOST=loki
      - TEMPO_HOST=tempo

  wise-task-gateway:
    image: ghcr.io/terross/wise-task-gateway:main
    depends_on:
      - wise-task-plugin
      - wise-task-profile
      - wise-task-graph
      - wise-task-task
    container_name: wise-task-gateway
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - LOKI_HOST=loki
      - TEMPO_HOST=tempo

  wise-task-mongo:
    image: mongo:latest
    container_name: wise-task-mongo
    ports:
      - "27017:27017"

  wise-task-db:
    image: postgres:13.1-alpine
    container_name: wise-task-db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=wise_task
      - POSTGRES_PASSWORD=wise_task

  tempo:
    image: grafana/tempo
    command: [ "-config.file=/etc/tempo.yaml" ]
    volumes:
      - ./docker/tempo/tempo-local.yml:/etc/tempo.yaml
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "14268"  # jaeger ingest
      - "9411:9411" # zipkin

  loki:
    image: grafana/loki
    command: [ "-config.file=/etc/loki/local-config.yaml" ]
    ports:
      - "3100:3100"
    environment:
      - JAEGER_AGENT_HOST=tempo
      - JAEGER_ENDPOINT=http://tempo:14268/api/traces
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1

  prometheus:
    image: prom/prometheus
    extra_hosts: [ 'host.docker.internal:host-gateway' ]
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    depends_on:
      - loki
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources
      - ./docker/grafana/dashboards:/etc/grafana/dashboards
      - ./docker/grafana/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_AUTH_BASIC_ENABLED="false"
      - GF_AUTH_DISABLE_LOGIN_FORM="true"
      - GF_AUTH_DISABLE_SIGNOUT_MENU="true"
      - GF_AUTH_PROXY_ENABLED="true"
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - loki
      - prometheus
    ports:
      - "3000:3000"