grpc:
  service:
    graph:
      host: localhost
      port: 6565
    profile:
      host: localhost
      port: 6567
    plugin:
      host: localhost
      port: 6566
    task:
      host: localhost
      port: 6568
server:
  port: 8083
