global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'wise-task-graph'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'wise-task-graph:8080' ]
  - job_name: 'wise-task-plugin'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'wise-task-plugin:8081' ]
  - job_name: 'wise-task-profile'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['wise-task-profile:8082']
  - job_name: 'wise-task-task'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'wise-task-task:8083' ]
  - job_name: 'wise-task-gateway'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'wise-task-gateway:8084' ]
  - job_name: 'wise-task-event-adapter'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'wise-task-event-adapter:8085' ]